name: mywebsite
description: Personal Website

publish_to: "none"

version: 1.3.17+18

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^11.5.0
  firebase_core: ^3.14.0
  firebase_core_web: ^2.23.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.7
  footer: ^0.0.4
  gap: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  package_info_plus: ^8.3.0
  responsive_framework: ^1.1.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.5
  version: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/projects/
    - assets/images/skills/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          style: normal
    - family: Anton
      fonts:
        - asset: assets/fonts/anton/Anton-Regular.ttf
          style: normal
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/poiret_one/PoiretOne-Regular.ttf
          style: normal

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
